#include <string>

#pragma once

namespace cmd {
    struct comand_w_description{
        std::string command;
        std::string description;
        bool command_alias;
    };

    //comand names
    enum command_name{
        HELP,
        HINT_ON,
        HINT_ON1,
        HINT_OFF,
        HINT_OFF1,
        QUIT,
        QUIT1,
        SCAN,
        OPEN,
        OPEN1,
        CLOSE,
        CLOSE1,
        REOPEN,
        REOPEN1,
        PORT,
        PORT1,
        SEND,
        SEND1,
        DIRECT,
        DIRECT1,
        DIRECT2,
        HALT,
        CLEAR,
        CLEAR1,
        CLEAR2,
        RESET_CLOCK,
        RESET_CLOCK1,
        RESET_CLOCK2,
        MAKE,
        MAKE1,
        EXEC,
        EXEC1,
        EEXEC,
        SAFE_EXEC,
        SAFE_EXEC1,
        SAFE_EXEC2,
        FIND,
        FIND1,
        FILE,
        FILE1,
        RESET_FILTERS,
        RESET_FILTERS1,
        RESET_FILTERS2,
        SAVE,
        SAVE1,
        LOAD,
        LOAD1,
        LOAD_LOG,
        LOAD_LOG1,
        HIGHLITING_OFF,
        HIGHLITING_OFF1,
        HIGHLITING_ON,
        HIGHLITING_ON1,
        FOLLOW_SIGN_ON,
        FOLLOW_SIGN_ON1,
        FOLLOW_SIGN_OFF,
        FOLLOW_SIGN_OFF1,
        TIME_OFF,
        TIME_OFF1,
        TIME_ON,
        TIME_ON1,
        PRECISIONS_TIME_ON,
        PRECISIONS_TIME_ON1,
        PRECISIONS_TIME_OFF,
        PRECISIONS_TIME_OFF1,
        FILE_LOCATION_ON,
        FILE_LOCATION_ON1,
        FILE_LOCATION_OFF,
        FILE_LOCATION_OFF1,
        FILE_SHORTTING_ON,
        FILE_SHORTTING_ON1,
        FILE_SHORTTING_OFF,
        FILE_SHORTTING_OFF1,
        PRIORITY_COLOR_ON,
        PRIORITY_COLOR_ON1,
        PRIORITY_COLOR_OFF,
        PRIORITY_COLOR_OFF1,
        DECORATION_ON,
        DECORATION_ON1,
        DECORATION_OFF,
        DECORATION_OFF1,
        HEAD,
        HEAD1,
        HIDE_ALL,
        HIDE_ALL1,
        HIDE_ALL2,
        SHOW_ALL,
        SHOW_ALL1,
        SHOW_ALL2,
        SHOW,
        SHOW1,
        HIDE,
        HIDE1,
        SHOW_ONLY,
        SHOW_ONLY1,
        HIDE_ONLY,
        HIDE_ONLY1,
        SHOW_RESET,
        SHOW_RESET1,
        SHOW_RESET2,
        SHOW_RETURN_ZERO_ON,
        SHOW_RETURN_ZERO_ON1,
        SHOW_RETURN_ZERO_OFF,
        SHOW_RETURN_ZERO_OFF1,
        USE_CONFIRM_CHARACTER_ON,
        USE_CONFIRM_CHARACTER_ON1,
        USE_CONFIRM_CHARACTER_OFF,
        USE_CONFIRM_CHARACTER_OFF1,
        RESET,
        RESET1,
        RESET2,
        UNDEFINED_PRIORITY,
        UNDEFINED_PRIORITY1,
        SAVE_ON_QUIT_ON,
        SAVE_ON_QUIT_ON1,
        SAVE_ON_QUIT_OFF,
        SAVE_ON_QUIT_OFF1,
        SAVE_ON_QUIT_OFF2,
        SAVE_SETTING,
        SAVE_SETTING1,
        SPEED_STAT,
        SPEED_STAT1,
        SPEED_STAT2,
        SPEED,
        SPEED1,
        SPEED2,
        PING,
        TEST,
        FTEST,
        MAX_COMMAND,
    };

    // command texts
    comand_w_description commands[MAX_COMMAND] = {
        {"help"                 ,"Zobrazí pomoc ovládání programu."                                                 ,false},
        {"hint off"             ,"Zapne doporučování příkazů."                                                      ,false},
        {"hiof"                 ,"Zapne doporučování příkazů."                                                      ,true},
        {"hint on"              ,"Vypne doporučování příkazů."                                                      ,false},
        {"hion"                 ,"Vypne doporučování příkazů."                                                      ,true},
        {"quit"                 ,"Zastaví program."                                                                 ,false},
        {"q"                    ,"Zastaví program."                                                                 ,true },
        {"scan"                 ,"Vypíše dostupné porty."                                                           ,false},
        {"open "                ,"Otevre port.(dovolene formaty jsou napr: 'COM3' '3').."                           ,false},
        {"o "                   ,"Otevre port.(dovolene formaty jsou napr: 'COM3' '3').."                           ,true },
        {"close"                ,"Zavře port."                                                                      ,false},
        {"c"                    ,"Zavře port."                                                                      ,true },
        {"reopen"               ,"Restartuje seriový port."                                                         ,false},
        {"r"                    ,"Restartuje seriový port."                                                         ,true },
        {"port"                 ,"Vypíše aktuálně otevřený port."                                                   ,false},
        {"p"                    ,"Vypíše aktuálně otevřený port."                                                   ,true },
        {"send "                ,"Pošle znaky na seriovou linku."                                                   ,false},
        {"s "                   ,"Pošle znaky na seriovou linku."                                                   ,true },
        {"direct_mode"          ,"Přepne program do módu kde odesílá vše z klavesnice po seriové lince. Z tohoto módu lze odejít zmáčknutím ESC." ,false},
        {"dp"                   ,"Přepne program do módu kde odesílá vše z klavesnice po seriové lince. Z tohoto módu lze odejít zmáčknutím ESC." ,true },
        {"dm"                   ,"Přepne program do módu kde odesílá vše z klavesnice po seriové lince. Z tohoto módu lze odejít zmáčknutím ESC." ,true },
        {"halt"                 ,"Dočasně zastaví seriovou linku."                                                  ,false},
        {"clear"                ,"Vymaže přijaté zprávy."                                                           ,false},
        {"cl"                   ,"Vymaže přijaté zprávy."                                                           ,true },
        {"cls"                  ,"Vymaže přijaté zprávy."                                                           ,true },
        {"reset_clock"          ,"Restartuje hodiny příchodu zpráv."                                                ,false},
        {"rstclk"               ,"Restartuje hodiny příchodu zpráv."                                                ,true },
        {"rc"                   ,"Restartuje hodiny příchodu zpráv."                                                ,true },
        {"make"                 ,"Spustí příkaz make. A vypisuje výstup."                                           ,false},
        {"make "                ,"Spustí příkaz make. A vypisuje výstup."                                           ,true },
        {"exec "                ,"Spustí příkaz. A vypisuje výstup."                                                ,false},
        {"e "                   ,"Spustí příkaz. A vypisuje výstup."                                                ,true },
        {"ee "                  ,"Spustí příkaz. A vypisuje výstup(po dokončení se zastaví nehledě na nastavení)."  ,false},
        {"exec_safe "           ,"Spustí příkaz. V režimu odpojené seriové linky."                                  ,false},
        {"execs "               ,"Spustí příkaz. V režimu odpojené seriové linky."                                  ,true },
        {"es "                  ,"Spustí příkaz. V režimu odpojené seriové linky."                                  ,true },
        {"find "                ,"Filtruje zpravy regulárním výrazem."                                              ,false},
        {"f "                   ,"Filtruje zpravy regulárním výrazem."                                              ,true },
        {"file "                ,"Filtrujeme jména souboru regulárním výrazem."                                     ,false},
        {"l "                   ,"Filtrujeme jména souboru regulárním výrazem."                                     ,true },
        {"reset_filter"         ,"Restartujeme filtry regulárních výrazů."                                          ,false},
        {"rstfilter"            ,"Restartujeme filtry regulárních výrazů."                                          ,true },
        {"rf"                   ,"Restartujeme filtry regulárních výrazů."                                          ,true },
        {"save "                ,"Uloží aktuální zprávy do souboru.(neukládá čas příchodu)."                        ,false},
        {"sv "                  ,"Uloží aktuální zprávy do souboru.(neukládá čas příchodu)."                        ,true },
        {"load "                ,"Načte soubor výpisu z seriové linky."                                             ,false},
        {"ld "                  ,"Načte soubor výpisu z seriové linky."                                             ,true },
        {"load_log"             ,"Načte zprávy které byli v aplikaci při posledním spuštění."                       ,false},
        {"ll"                   ,"Načte zprávy které byli v aplikaci při posledním spuštění."                       ,true },
        {"highliting off"       ,"Vypne zvýrazňování v textu (ERROR se zvýrazní červeně)(linka na konci s ! dostane warning prioritu pokud žádnou nemá)." ,false},
        {"hof"                  ,"Vypne zvýrazňování v textu (ERROR se zvýrazní červeně)(linka na konci s ! dostane warning prioritu pokud žádnou nemá)." ,true },
        {"highliting on"        ,"Zapne zvýrazňování v textu (ERROR se zvýrazní červeně)(linka na konci s ! dostane warning prioritu pokud žádnou nemá)." ,false},
        {"hon"                  ,"Zapne zvýrazňování v textu (ERROR se zvýrazní červeně)(linka na konci s ! dostane warning prioritu pokud žádnou nemá)." ,true },
        {"folowing_sign on"     ,"Zapne znaménko před folower linkou."                                              ,false},
        {"flwron"               ,"Zapne znaménko před folower linkou."                                              ,true },
        {"folowing_sign off"    ,"Vypne znaménko před folower linkou."                                              ,false},
        {"flwrof"               ,"Vypne znaménko před folower linkou."                                              ,true },
        {"time off"             ,"Vypne zobrazování času příchodu."                                                 ,false},
        {"tof"                  ,"Vypne zobrazování času příchodu."                                                 ,true },
        {"time on"              ,"Zapne zobrazování času příchodu."                                                 ,false},
        {"ton"                  ,"Zapne zobrazování času příchodu."                                                 ,true },
        {"precision_time on"    ,"Nastaví formát času na MILLISECONDS"                                              ,false},
        {"pto"                  ,"Nastaví formát času na MILLISECONDS"                                              ,true },
        {"precision_time off"   ,"Nastaví formát času na HOD:MIN:SEC"                                               ,false},
        {"ptf"                  ,"Nastaví formát času na HOD:MIN:SEC"                                               ,true },
        {"file_location on"     ,"Zobrazí soubor a řádek logu."                                                     ,false},
        {"fon"                  ,"Zobrazí soubor a řádek logu."                                                     ,true },
        {"file_location off"    ,"Skryje soubor a řádek logu."                                                      ,false},
        {"fof"                  ,"Skryje soubor a řádek logu."                                                      ,true },
        {"file_shorting on"     ,"Zobrazí pouze jméno souboru bez cesty."                                           ,false},
        {"fson"                 ,"Zobrazí pouze jméno souboru bez cesty."                                           ,true },
        {"file_shorting off"    ,"Zobrazí i celou cestu pokud jí soubor má."                                        ,false},
        {"fsof"                 ,"Zobrazí i celou cestu pokud jí soubor má."                                        ,true },
        {"priority_color on"    ,"Zapne barvy priorit."                                                             ,false},
        {"pcon"                 ,"Zapne barvy priorit."                                                             ,true },
        {"priority_color off"   ,"Vypne barvy priorit."                                                             ,false},
        {"pcof"                 ,"Vypne barvy priorit."                                                             ,true },
        {"decoration on"        ,"Zapne výchozí dekorace logů."                                                     ,false},
        {"don"                  ,"Zapne výchozí dekorace logů."                                                     ,true },
        {"decoration off"       ,"Vypne veškeré dekorace logů."                                                     ,false},
        {"dof"                  ,"Vypne veškeré dekorace logů."                                                     ,true },
        {"head "                ,"Nastaví minimální odsazení řádků."                                                ,false},
        {"of "                  ,"Nastaví minimální odsazení řádků."                                                ,true },
        {"hide all"             ,"Skryje všechny typy zpráv."                                                       ,false},
        {"hal"                  ,"Skryje všechny typy zpráv."                                                       ,true },
        {"hall"                 ,"Skryje všechny typy zpráv."                                                       ,true },
        {"show all"             ,"Zobrazí všechny typy zpráv."                                                      ,false},
        {"sal"                  ,"Zobrazí všechny typy zpráv."                                                      ,true },
        {"sall"                 ,"Zobrazí všechny typy zpráv."                                                      ,true },
        {"show "                ,"Ukáže typ zprávy. Možné typy zpráv: normal,debug,info,warning,error,ok,silent,testok,testnok,all a jejich aliasi: n,dbg/d,i,wrng/w,err/e,k,sil/s,tok/tk,ton/tn." ,false},
        {"sh "                  ,"Ukáže typ zprávy. Možné typy zpráv: normal,debug,info,warning,error,ok,silent,testok,testnok,all a jejich aliasi: n,dbg/d,i,wrng/w,err/e,k,sil/s,tok/tk,ton/tn." ,true },
        {"hide "                ,"Skryje typ zprávy. Možné typy zpráv: normal,debug,info,warning,error,ok,silent,testok,testnok,all a jejich aliasi: n,dbg/d,i,wrng/w,err/e,k,sil/s,tok/tk,ton/tn" ,false},
        {"hi "                  ,"Skryje typ zprávy. Možné typy zpráv: normal,debug,info,warning,error,ok,silent,testok,testnok,all a jejich aliasi: n,dbg/d,i,wrng/w,err/e,k,sil/s,tok/tk,ton/tn" ,true },
        {"show_only "           ,"Ukáže jeden typ zprávy. Možné typy zpráv: normal,debug,info,warning,error,ok,silent,testok,testnok,all a jejich aliasi: n,dbg/d,i,wrng/w,err/e,k,sil/s,tok/tk,ton/tn." ,false},
        {"so "                  ,"Ukáže jeden typ zprávy. Možné typy zpráv: normal,debug,info,warning,error,ok,silent,testok,testnok,all a jejich aliasi: n,dbg/d,i,wrng/w,err/e,k,sil/s,tok/tk,ton/tn." ,true },
        {"hide_only "           ,"Skryje jeden typ zprávy. Možné typy zpráv: normal,debug,info,warning,error,ok,silent,testok,testnok,all a jejich aliasi: n,dbg/d,i,wrng/w,err/e,k,sil/s,tok/tk,ton/tn.",false},
        {"ho "                  ,"Skryje jeden typ zprávy. Možné typy zpráv: normal,debug,info,warning,error,ok,silent,testok,testnok,all a jejich aliasi: n,dbg/d,i,wrng/w,err/e,k,sil/s,tok/tk,ton/tn.",true },
        {"show reset"           ,"Ukáže zprávy které jsou ve výchozím nastavení vyditelné."                        ,false},
        {"sr"                   ,"Ukáže zprávy které jsou ve výchozím nastavení vyditelné."                        ,true },
        {"sor"                  ,"Ukáže zprávy které jsou ve výchozím nastavení vyditelné."                        ,true },
        {"show_return_zero on"  ,"Automaticky dokončit process který skončil návratovou hodnotou 0."               ,false},
        {"srz"                  ,"Automaticky dokončit process který skončil návratovou hodnotou 0."               ,true },
        {"show_return_zero off" ,"Zastavit se po dokončení programu i pokud skončil návratovou hodnotou 0."        ,false},
        {"hrz"                  ,"Zastavit se po dokončení programu i pokud skončil návratovou hodnotou 0."        ,true },
        {"use_confirm_character on"  ,"Po potvrzení čekací obrazovky se potvzovací znak i zapíše do příkazu."      ,false},
        {"ucch"                 ,"Po potvrzení čekací obrazovky se potvzovací znak i zapíše do příkazu."           ,true},
        {"use_confirm_character off" ,"Po potvrzení čekací obrazovky se potvzovací znak zahodí."                   ,false},
        {"dcch"                 ,"Po potvrzení čekací obrazovky se potvzovací znak zahodí."                        ,true},
        {"reset"                ,"Resetuje veškeré filtry, jak souboru tak textu tak priority."                    ,false},
        {"rst"                  ,"Resetuje veškeré filtry, jak souboru tak textu tak priority."                    ,true},
        {"rs"                   ,"Resetuje veškeré filtry, jak souboru tak textu tak priority."                    ,true},
        {"undefined_priority "  ,"Nastaví výchozí prioritu pro zprávy bez priority."                               ,false},
        {"ndef "                ,"Nastaví výchozí prioritu pro zprávy bez priority."                               ,true},
        {"save_on_quit on"      ,"Obnoví ukládání nastavení na konci programu."                                    ,false},
        {"do_save"              ,"Obnoví ukládání nastavení na konci programu."                                    ,true},
        {"save_on_quit off"     ,"Zamezí na konci programu uložení nastavení."                                     ,false},
        {"dont_save"            ,"Zamezí na konci programu uložení nastavení."                                     ,true},
        {"ds"                   ,"Zamezí na konci programu uložení nastavení."                                     ,true},
        {"save_settings"        ,"Uloží aktuální nastavení."                                                       ,false},
        {"sas"                  ,"Uloží aktuální nastavení."                                                       ,true},
        {"speed"                ,"Ukáže rychlost seriového portu"                                                  ,false},
        {"bound"                ,"Ukáže rychlost seriového portu"                                                  ,true},
        {"bd"                   ,"Ukáže rychlost seriového portu"                                                  ,true},
        {"speed "               ,"Nastaví rychlost seriového portu"                                                ,false},
        {"bound "               ,"Nastaví rychlost seriového portu"                                                ,true},
        {"bd "                  ,"Nastaví rychlost seriového portu"                                                ,true},
        {"ping"                 ,"Response text test"                                                              ,false},
        {"test"                 ,"Print test"                                                                      ,false},
        {"ftest"                ,"Folower test"                                                                    ,false},
    };

    // funkce pro zpřehlednění mainu
    inline std::string name(command_name name){
        return commands[name].command;
    }

        // funkce pro zpřehlednění mainu
    inline int name_len(command_name name){
        return commands[name].command.length();
    }
};